# Generated by Django 5.2.17 on 2026-09-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MiningAnalyticsSyncState",
            fields=[
                ("source_name", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("last_processed_rowid", models.PositiveBigIntegerField(default=0)),
                ("backfill_target_rowid", models.PositiveBigIntegerField(null=True)),
                ("initialized", models.BooleanField(default=False)),
                ("material_signature", models.CharField(default="", max_length=64)),
                ("generation", models.PositiveBigIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(null=True)),
                ("last_reconciled_at", models.DateTimeField(null=True)),
                ("last_error", models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name="MiningMaterialDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("player_uuid", models.CharField(max_length=32)),
                ("world_id", models.PositiveIntegerField()),
                ("material_key", models.SlugField(max_length=64)),
                ("break_count", models.PositiveBigIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["material_key", "date"], name="mining_material_date"),
                    models.Index(
                        fields=["world_id", "material_key", "date"],
                        name="mining_world_material_date",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "player_uuid", "world_id", "material_key"),
                        name="mining_daily_identity",
                    )
                ],
            },
        ),
    ]
