# Generated by Django 5.2.17 on 2026-09-16 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("auth.discord.succeeded", "Authenticated with Discord"),
                            ("auth.discord.denied", "Discord authentication denied"),
                            ("auth.logout", "Signed out"),
                            ("page.dashboard.viewed", "Viewed Dashboard"),
                            ("page.code_of_conduct.viewed", "Viewed Code of Conduct"),
                            ("page.ore_overview.viewed", "Viewed Ore Statistics overview"),
                            ("analytics.diamonds.viewed", "Viewed Diamond Statistics"),
                            ("analytics.ancient_debris.viewed", "Viewed Ancient Debris Statistics"),
                            ("analytics.emerald.viewed", "Viewed Emerald Statistics"),
                            ("analytics.filtered", "Applied mining filters"),
                            ("analytics.threshold_changed", "Changed sample threshold"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("denied", "Denied"),
                            ("error", "Error"),
                            ("info", "Info"),
                        ],
                        max_length=8,
                    ),
                ),
                ("actor_discord_id", models.CharField(max_length=20, null=True)),
                ("actor_display_name", models.CharField(blank=True, max_length=80)),
                ("actor_username", models.CharField(blank=True, max_length=80)),
                ("request_method", models.CharField(max_length=10)),
                ("request_path", models.CharField(max_length=512)),
                ("request_query", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("referer", models.CharField(blank=True, max_length=512)),
                ("host", models.CharField(blank=True, max_length=255)),
                ("accept_language", models.CharField(blank=True, max_length=128)),
                ("metadata_json", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(fields=["-created_at", "-id"], name="audit_newest"),
                    models.Index(
                        fields=["actor_discord_id", "-created_at"], name="audit_actor_time"
                    ),
                    models.Index(fields=["event_type", "-created_at"], name="audit_event_time"),
                    models.Index(fields=["result", "-created_at"], name="audit_result_time"),
                ],
            },
        ),
    ]
